Link Visit to Nurse Views
Brayzure/CSE360Project pull request #5
Opened 2024-04-03 22:03 UTC by carodr50

2024-04-05 02:35 UTC, Brayzure requested changes
Left a couple comments, otherwise looks good.

2024-04-05 02:35 UTC, Brayzure commented on src/application/healthSoftware/views/VisitExamQuestions.java
> +		TextField allergiesField = (TextField) allergiesInput.getChildren().get(0);
Got an error, pretty sure these should be `TextArea`, not `TextField`.

2024-04-05 02:35 UTC, Brayzure commented on src/application/healthSoftware/views/VisitExamQuestions.java
> +		TextField healthConcernsField = (TextField) healthConcernsInput.getChildren().get(0);
Here too.

2024-04-07 06:43 UTC, carodr50 commented
Those should be fixed now

2024-04-08 06:55 UTC, merged